# Generated by Django 3.0.2 on 2020-02-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.IntegerField(choices=[(0, 'Problem Giver'), (1, 'Problem Solver')], default=0),
        ),
    ]
