# Generated by Django 3.0.2 on 2020-01-26 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techmed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
