# Generated by Django 3.0.2 on 2020-02-04 00:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('techmed', '0004_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2020, 2, 4, 0, 59, 37, 501239, tzinfo=utc), max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
